"use client";

import { useState } from "react";
import type { Booking, Event, Profile } from "@/lib/types";
import styles from "../volunteer.module.css";

export default function EventModal({ event, bookings, profile, onClose, onBook }: { event: Event | null; bookings: Booking[]; profile: Profile | null; onClose: () => void; onBook: (event: Event, selectedSlot: string) => Promise<string | null> }) {
  const [selectedSlot, setSelectedSlot] = useState(""); const [message, setMessage] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false);
  if (!event) return null;
  const activeEvent = event;
  const ranges = activeEvent.time_slots.split(",").map((slot) => slot.trim()).filter(Boolean);
  async function submit(formEvent: React.FormEvent) { formEvent.preventDefault(); if (!selectedSlot) return; setIsSubmitting(true); const error = await onBook(activeEvent, selectedSlot); setIsSubmitting(false); if (error) { setMessage(error); return; } onClose(); }
  return <div className={styles.backdrop} role="presentation" onMouseDown={(clickEvent) => { if (clickEvent.target === clickEvent.currentTarget) onClose(); }}><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="event-modal-title"><div className={styles.modalHeader}><div><h2 id="event-modal-title" className={styles.cardTitle}>{activeEvent.title}</h2><p className={styles.cardHint}>{activeEvent.date} · {activeEvent.location}</p></div><button type="button" className={styles.closeButton} onClick={onClose} aria-label="Close event">×</button></div><div className={styles.eventDetails}><span>Capacity: {activeEvent.total_slots} volunteers</span>{activeEvent.description && <p className={styles.description}>{activeEvent.description}</p>}</div><form onSubmit={submit}><div className={styles.field}><label className={styles.fieldLabel} htmlFor="time-range">Choose a time range</label><select id="time-range" className={styles.select} required value={selectedSlot} onChange={(changeEvent) => setSelectedSlot(changeEvent.target.value)}><option value="">Select a time range</option>{ranges.map((range) => { const isTakenByYou = bookings.some((booking) => booking.event_id === activeEvent.id && booking.selected_slot === range); return <option key={range} value={range} disabled={isTakenByYou}>{range}{isTakenByYou ? " (already selected)" : ""}</option>; })}</select></div><div className={styles.signedInAs}>Booking as <strong>{profile?.full_name || profile?.email || "Volunteer"}</strong></div>{message && <div className={styles.messageError} role="alert">{message}</div>}<div className={styles.modalActions}><button type="button" className={styles.secondaryButton} onClick={onClose}>Cancel</button><button type="submit" className={styles.primaryButton} disabled={isSubmitting}>{isSubmitting ? "Booking..." : "Book this shift"}</button></div></form></section></div>;
}
