import { hasEventFinished } from "@/lib/date-utils";
import type { Event, EventSlot } from "@/lib/types";
import styles from "../volunteer.module.css";
import EmptyState from "./EmptyState";

function formatEventDate(date: string) { return new Intl.DateTimeFormat("en-ZA", { weekday: "short", day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(new Date(`${date}T00:00:00`)); }
const formatTime = (value: string) => value.slice(0, 5);

export default function UpcomingEvents({ events, eventSlots, isLoading, isUserBookedForEvent, onSelect }: { events: Event[]; eventSlots: EventSlot[]; isLoading: boolean; isUserBookedForEvent: (eventId: number) => boolean; onSelect: (event: Event) => void }) {
  const upcomingEvents = events.filter((event) => event.status !== "Cancelled" && !hasEventFinished(event, eventSlots)).sort((first, second) => first.date.localeCompare(second.date));
  return <section id="upcoming-events" className={styles.card}><div className={styles.cardHeader}><div><h2 className={styles.cardTitle}>Upcoming events</h2><p className={styles.cardHint}>Choose an event to view its shift ranges and reserve your place.</p></div><span className={styles.eventCount}>{upcomingEvents.length}</span></div>{isLoading ? <div className={styles.emptySmall}>Loading upcoming events...</div> : upcomingEvents.length === 0 ? <EmptyState icon="calendar" title="No upcoming events yet" description="New opportunities will appear here as soon as they are scheduled." ctaLabel="Browse Events" ctaHref="/volunteer#upcoming-events" /> : <div className={styles.upcomingList}>{upcomingEvents.map((event) => { const booked = isUserBookedForEvent(event.id); const slots = eventSlots.filter((slot) => slot.event_id === event.id); return <article className={styles.upcomingEvent} key={event.id}><div className={styles.eventDate}><span className={styles.eventDateDay}>{new Date(`${event.date}T00:00:00`).getUTCDate()}</span><span className={styles.eventDateMonth}>{new Intl.DateTimeFormat("en-ZA", { month: "short", timeZone: "UTC" }).format(new Date(`${event.date}T00:00:00`))}</span></div><div className={styles.upcomingDetails}><h3 className={styles.upcomingTitle}>{event.title}</h3><p className={styles.upcomingMeta}>{formatEventDate(event.date)} · {event.location}</p><p className={styles.upcomingSlots}>{slots.length > 0 ? slots.map((slot) => `${formatTime(slot.start_time)}-${formatTime(slot.end_time)} (${slot.capacity})`).join(" · ") : "Schedule coming soon"}</p></div><div className={styles.eventAction}><span className={booked ? styles.bookedStatus : slots.length > 0 ? styles.availableStatus : styles.bookedStatus}>{booked ? "Your shift" : slots.length > 0 ? "Available" : "Not yet open"}</span><button type="button" className={booked ? styles.secondaryButton : styles.primaryButton} onClick={() => onSelect(event)}>{booked ? "View booking" : "View event"}</button></div></article>; })}</div>}</section>;
}
