-- REQUIRES DATABASE ADMIN REVIEW - NOT YET APPLIED
-- Additive feature migration against the supplied live schema, not a baseline.
begin;

create table public.corporate_companies (
  id bigint generated by default as identity primary key,
  name text not null check (btrim(name) <> ''),
  industry text, website text, location text,
  contact_name text, contact_email text, contact_phone text,
  relationship_status text not null default 'Lead'
    check (relationship_status in ('Lead','Contacted','Interested','Active Partner','Inactive')),
  charities_supported integer
    check (charities_supported is null or charities_supported >= 0),
  estimated_annual_csr numeric(14,2)
    check (estimated_annual_csr >= 0 and estimated_annual_csr <> 'NaN'::numeric),
  csr_focus_areas text,
  partnership_potential text not null default 'Medium'
    check (partnership_potential in ('Low','Medium','High')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.corporate_bookings (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.corporate_companies(id) on delete restrict,
  event_id bigint not null references public.events(id) on delete restrict,
  event_slot_id bigint not null references public.event_slots(id) on delete restrict,
  contact_name text, contact_email text,
  team_size integer not null check (team_size > 0),
  status text not null default 'Pending' check (status in ('Pending','Confirmed','Completed','Cancelled')),
  notes text, attendance_count integer, volunteer_hours numeric(12,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint corporate_attendance_valid check (
    (status = 'Completed' and attendance_count is not null and volunteer_hours is not null
      and attendance_count between 0 and team_size and volunteer_hours >= 0 and volunteer_hours <> 'NaN'::numeric
      and (attendance_count > 0 or volunteer_hours = 0))
    or (status <> 'Completed' and attendance_count is null and volunteer_hours is null)
  )
);
create index corporate_bookings_slot_idx on public.corporate_bookings(event_slot_id);
create index corporate_bookings_event_idx on public.corporate_bookings(event_id);
create index corporate_bookings_company_idx on public.corporate_bookings(company_id);

-- The audit reason distinguishes an admin/company cancellation from an event-triggered cancellation.
alter table public.corporate_bookings add column cancellation_reason text;

create table public.corporate_notes (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.corporate_companies(id) on delete restrict,
  body text not null check (btrim(body) <> ''),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index corporate_notes_company_idx on public.corporate_notes(company_id);

create table public.organisation_settings (
  id integer primary key default 1 check (id = 1),
  organisation_name text not null default 'Ladles of Love' check (btrim(organisation_name) <> ''),
  default_location text not null default '', contact_email text not null default '',
  timezone text not null default 'Africa/Johannesburg' check (timezone = 'Africa/Johannesburg'),
  booking_confirmation_enabled boolean not null default false,
  booking_cancellation_enabled boolean not null default false,
  shift_reminder_enabled boolean not null default false,
  corporate_booking_confirmation_enabled boolean not null default false,
  updated_at timestamptz not null default now()
);
insert into public.organisation_settings(id) values (1);

alter table public.corporate_companies enable row level security;
alter table public.corporate_bookings enable row level security;
alter table public.corporate_notes enable row level security;
alter table public.organisation_settings enable row level security;

revoke all on public.corporate_companies, public.corporate_bookings,
  public.corporate_notes, public.organisation_settings from public, anon, authenticated;
grant select, insert, update on public.corporate_companies to authenticated;
grant select on public.corporate_bookings to authenticated;
grant select, insert on public.corporate_notes to authenticated;
grant select, update on public.organisation_settings to authenticated;
-- Clear possible Supabase/default sequence grants, including setval privileges.
revoke all on sequence public.corporate_companies_id_seq,
  public.corporate_bookings_id_seq, public.corporate_notes_id_seq
  from public, anon, authenticated;
grant usage on sequence public.corporate_companies_id_seq, public.corporate_notes_id_seq to authenticated;

create policy corporate_companies_admin_select on public.corporate_companies for select to authenticated using ((select public.is_admin()));
create policy corporate_companies_admin_insert on public.corporate_companies for insert to authenticated with check ((select public.is_admin()));
create policy corporate_companies_admin_update on public.corporate_companies for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy corporate_bookings_admin_select on public.corporate_bookings for select to authenticated using ((select public.is_admin()));
create policy corporate_notes_admin_select on public.corporate_notes for select to authenticated using ((select public.is_admin()));
create policy corporate_notes_admin_insert on public.corporate_notes for insert to authenticated with check ((select public.is_admin()) and created_by = (select auth.uid()));
create policy organisation_settings_admin_select on public.organisation_settings for select to authenticated using ((select public.is_admin()));
create policy organisation_settings_admin_update on public.organisation_settings for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

create function public.csr_touch_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin new.updated_at := now(); return new; end;
$$;
revoke all on function public.csr_touch_updated_at() from public, anon, authenticated;
create trigger corporate_companies_updated before update on public.corporate_companies for each row execute function public.csr_touch_updated_at();
create trigger corporate_bookings_updated before update on public.corporate_bookings for each row execute function public.csr_touch_updated_at();
create trigger organisation_settings_updated before update on public.organisation_settings for each row execute function public.csr_touch_updated_at();

-- All non-cancelled corporate rows retain their reserved places, including history.
-- Internal helper: never expose corporate totals or contact information through it.
create function public.csr_reserved_spaces(p_slot_id bigint, p_exclude_id bigint default null)
returns bigint language sql stable security definer set search_path = '' as $$
  select coalesce(sum(team_size), 0)::bigint from public.corporate_bookings
  where event_slot_id = p_slot_id and status <> 'Cancelled'
    and (p_exclude_id is null or id <> p_exclude_id);
$$;
revoke all on function public.csr_reserved_spaces(bigint,bigint) from public, anon, authenticated;

-- One controlled entry point for create, resize, move, cancellation, reactivation,
-- and aggregate attendance. Direct corporate booking writes are not granted.
create function public.save_corporate_booking(
  p_id bigint, p_company_id bigint, p_event_slot_id bigint, p_team_size integer,
  p_status text, p_contact_name text, p_contact_email text, p_notes text,
  p_attendance_count integer default null, p_volunteer_hours numeric default null
) returns public.corporate_bookings
language plpgsql security definer set search_path = '' as $$
declare
  v_old public.corporate_bookings%rowtype;
  v_slot public.event_slots%rowtype;
  v_event public.events%rowtype;
  v_result public.corporate_bookings%rowtype;
  v_count bigint;
  v_new_reservation boolean;
begin
  if auth.uid() is null or not public.is_admin() then raise exception 'Only administrators can manage corporate bookings.'; end if;
  -- Slot locks serialize writers, but cannot refresh a REPEATABLE READ snapshot.
  -- PostgreSQL READ UNCOMMITTED has the same snapshot semantics as READ COMMITTED.
  if pg_catalog.current_setting('transaction_isolation') not in ('read committed', 'read uncommitted') then
    raise exception 'Shared capacity mutations require READ COMMITTED isolation.' using errcode = '25000';
  end if;
  if p_team_size is null or p_team_size <= 0 then raise exception 'Team size must be a positive integer.'; end if;
  if p_status is null or p_status not in ('Pending','Confirmed','Completed','Cancelled') then raise exception 'Invalid corporate booking status.'; end if;
  -- Validate raw hours before numeric(12,2) rounding can turn -0.001 or 0.001 into zero.
  -- The table constraint still enforces NULL, NaN, bounds and status combinations.
  if p_volunteer_hours < 0 or (p_attendance_count = 0 and p_volunteer_hours > 0) then
    raise exception 'Hours must be nonnegative and must be zero when attendance is zero.';
  end if;
  if not exists (select 1 from public.corporate_companies where id = p_company_id) then raise exception 'Company no longer exists.'; end if;
  if p_id is not null then
    select * into v_old from public.corporate_bookings where id = p_id for update;
    if not found then raise exception 'Corporate booking no longer exists.'; end if;
  elsif p_status not in ('Pending','Confirmed') then
    raise exception 'New bookings must be Pending or Confirmed.';
  end if;
  -- Deterministic order prevents opposing moves from locking slots in reverse order.
  perform id from public.event_slots where id in (p_event_slot_id, v_old.event_slot_id) order by id for update;
  select * into v_slot from public.event_slots where id = p_event_slot_id for update;
  if not found then raise exception 'This event slot no longer exists.'; end if;
  select * into v_event from public.events where id = v_slot.event_id;
  if not found then raise exception 'This event no longer exists.'; end if;
  v_new_reservation := p_id is null or p_event_slot_id <> v_old.event_slot_id
    or p_team_size > v_old.team_size or (v_old.status = 'Cancelled' and p_status <> 'Cancelled');
  if v_new_reservation then
    if v_event.status = 'Cancelled' then raise exception 'This event has been cancelled and can no longer be booked.'; end if;
    if v_event.date is null
      or v_event.date::date < (now() at time zone 'Africa/Johannesburg')::date
      or (v_event.date::date = (now() at time zone 'Africa/Johannesburg')::date
        and v_slot.end_time <= (now() at time zone 'Africa/Johannesburg')::time) then
      raise exception 'This event slot has already ended and cannot be booked.';
    end if;
  end if;
  if p_status = 'Completed' then
    if v_event.status = 'Cancelled' or v_event.date is null
       or (v_event.date::date + v_slot.end_time) > (now() at time zone 'Africa/Johannesburg') then
      raise exception 'Attendance can only be completed for an ended, non-cancelled shift.';
    end if;
  end if;
  if v_old.status = 'Completed' and (p_status <> 'Completed' or p_event_slot_id <> v_old.event_slot_id or p_company_id <> v_old.company_id or p_team_size <> v_old.team_size) then
    raise exception 'Completed booking identity and reservation must be retained; only correct attendance or contact details.';
  end if;
  if p_status <> 'Cancelled' then
    select count(*) into v_count from public.bookings where event_slot_id = v_slot.id;
    if v_count + public.csr_reserved_spaces(v_slot.id, p_id) + p_team_size > v_slot.capacity then
      raise exception 'The team exceeds the remaining capacity of this time slot.';
    end if;
  end if;
  if p_id is null then
    insert into public.corporate_bookings(company_id,event_id,event_slot_id,team_size,status,contact_name,contact_email,notes,attendance_count,volunteer_hours)
    values(p_company_id,v_slot.event_id,v_slot.id,p_team_size,p_status,p_contact_name,p_contact_email,p_notes,p_attendance_count,p_volunteer_hours)
    returning * into v_result;
  else
    update public.corporate_bookings set company_id=p_company_id,event_id=v_slot.event_id,event_slot_id=v_slot.id,
      team_size=p_team_size,status=p_status,contact_name=p_contact_name,contact_email=p_contact_email,notes=p_notes,
      cancellation_reason = case when p_status = 'Cancelled' then
        case when v_event.status = 'Cancelled' then 'Parent event cancelled' else 'Company/admin cancelled' end
        else null end,
      attendance_count=p_attendance_count,volunteer_hours=p_volunteer_hours where id=p_id returning * into v_result;
  end if;
  return v_result;
end;
$$;
revoke all on function public.save_corporate_booking(bigint,bigint,bigint,integer,text,text,text,text,integer,numeric) from public, anon, authenticated;
grant execute on function public.save_corporate_booking(bigint,bigint,bigint,integer,text,text,text,text,integer,numeric) to authenticated;

-- Keep event cancellation and release of Pending/Confirmed corporate capacity in one transaction.
create function public.cancel_event_with_corporate_bookings(p_event_id bigint, p_message text default null)
returns public.events
language plpgsql security definer set search_path = 'public' as $$
declare
  v_event public.events%rowtype;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Only administrators can cancel events.';
  end if;
  select * into v_event from public.events where id = p_event_id for update;
  if not found then raise exception 'The event no longer exists.'; end if;

  -- Lock all related rows before either mutation and preserve completed history.
  perform id from public.corporate_bookings where event_id = p_event_id order by id for update;
  if exists (select 1 from public.corporate_bookings where event_id = p_event_id and status = 'Completed') then
    raise exception 'This event has completed attendance records and cannot be cancelled without resolving them first.';
  end if;

  update public.corporate_bookings
  set status = 'Cancelled', cancellation_reason = 'Parent event cancelled'
  where event_id = p_event_id and status in ('Pending', 'Confirmed');

  -- The existing cancellation function retains its validation and notification behavior.
  perform public.cancel_event(p_event_id, p_message);
  select * into v_event from public.events where id = p_event_id;
  return v_event;
end;
$$;
revoke all on function public.cancel_event_with_corporate_bookings(bigint,text) from public, anon, authenticated;
grant execute on function public.cancel_event_with_corporate_bookings(bigint,text) to authenticated;

-- Privacy-safe shared availability; no identities or separate corporate counts.
create function public.get_slot_availability()
returns table(event_slot_id bigint, remaining bigint)
language sql stable security definer set search_path = '' as $$
  select s.id, greatest(0::bigint, s.capacity - (select count(*) from public.bookings b where b.event_slot_id=s.id)
    - public.csr_reserved_spaces(s.id))
  from public.event_slots s where auth.uid() is not null order by s.id;
$$;
revoke all on function public.get_slot_availability() from public, anon, authenticated;
grant execute on function public.get_slot_availability() to authenticated;

CREATE OR REPLACE FUNCTION public.book_event_slot(p_event_slot_id bigint)
RETURNS bookings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_user_id uuid := auth.uid();
  v_slot public.event_slots%rowtype;
  v_profile public.profiles%rowtype;
  v_event_date date;
  v_event_status text;
  v_booking_count integer;
  v_booking public.bookings%rowtype;
begin
  if v_user_id is null then
    raise exception 'You must be signed in to book an event.';
  end if;

  select *
  into v_slot
  from public.event_slots
  where id = p_event_slot_id
  for update;

  if not found then
    raise exception 'This event slot no longer exists.';
  end if;

  select e.date::date, e.status
  into v_event_date, v_event_status
  from public.events e
  where e.id = v_slot.event_id;

  if not found then
    raise exception 'This event no longer exists.';
  end if;

  if v_event_status = 'Cancelled' then
    raise exception 'This event has been cancelled and can no longer be booked.';
  end if;

  if v_event_date < (now() at time zone 'Africa/Johannesburg')::date
    or (v_event_date = (now() at time zone 'Africa/Johannesburg')::date
      and v_slot.end_time <= (now() at time zone 'Africa/Johannesburg')::time) then
    raise exception 'This event slot has already ended and cannot be booked.';
  end if;

  select *
  into v_profile
  from public.profiles
  where id = v_user_id
    and role = 'volunteer';

  if not found then
    raise exception 'Only volunteer accounts can book event slots.';
  end if;

  if exists (
    select 1
    from public.bookings b
    where b.event_id = v_slot.event_id
      and b.user_id = v_user_id
  ) then
    raise exception 'You already have a booking for this event.';
  end if;

  select count(*)
  into v_booking_count
  from public.bookings b
  where b.event_slot_id = v_slot.id;

  if v_booking_count + public.csr_reserved_spaces(v_slot.id) >= v_slot.capacity then
    raise exception 'This time slot is already full.';
  end if;

  insert into public.bookings (
    event_id,
    event_slot_id,
    user_id,
    volunteer_name,
    volunteer_email,
    selected_slot,
    status
  )
  values (
    v_slot.event_id,
    v_slot.id,
    v_user_id,
    v_profile.full_name,
    v_profile.email,
    to_char(v_slot.start_time, 'HH24:MI')
      || '-'
      || to_char(v_slot.end_time, 'HH24:MI'),
    'Confirmed'
  )
  returning * into v_booking;

  return v_booking;
end;
$function$;

CREATE OR REPLACE FUNCTION public.save_event_with_slots(
  p_event_id bigint,
  p_title text,
  p_date date,
  p_location text,
  p_slots jsonb
)
RETURNS events
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_event public.events%rowtype;
  v_slot jsonb;
  v_start_time time;
  v_end_time time;
  v_capacity integer;
  v_slot_id bigint;
  v_reserved bigint;
  v_seen_ids bigint[] := ARRAY[]::bigint[];
  v_existing_slot public.event_slots%rowtype;
  v_time_slots text;
  v_total_slots integer;
begin
  if not public.is_admin() then
    raise exception 'Only administrators can manage events.';
  end if;

  if trim(p_title) = ''
    or p_date is null
    or trim(p_location) = '' then
    raise exception 'Title, date, and location are required.';
  end if;

  if jsonb_typeof(p_slots) <> 'array'
    or jsonb_array_length(p_slots) = 0 then
    raise exception 'Add at least one time slot.';
  end if;

  if p_event_id is null then

    insert into public.events (
      title,
      date,
      location,
      time_slots,
      total_slots
    )
    values (
      trim(p_title),
      to_char(p_date, 'YYYY-MM-DD'),
      trim(p_location),
      '',
      0
    )
    returning *
    into v_event;

  else

    select *
    into v_event
    from public.events
    where id = p_event_id
    for update;

    if not found then
      raise exception 'The event no longer exists.';
    end if;

    -- Serialize slot edits with both individual and corporate reservations.
    perform id from public.event_slots where event_id = p_event_id order by id for update;

    -- Metadata and non-invalidating slot edits remain possible after bookings.
    if v_event.date::date is distinct from p_date and (
      exists (select 1 from public.bookings where event_id = p_event_id)
      or exists (select 1 from public.corporate_bookings where event_id = p_event_id)
    ) then
      raise exception 'An event date cannot change after bookings exist.';
    end if;

    update public.events
    set
      title = trim(p_title),
      date = to_char(p_date, 'YYYY-MM-DD'),
      location = trim(p_location)
    where id = p_event_id
    returning *
    into v_event;

  end if;

  for v_slot in
    select value
    from jsonb_array_elements(p_slots)
  loop

    v_start_time :=
      (v_slot ->> 'start_time')::time;

    v_end_time :=
      (v_slot ->> 'end_time')::time;

    v_capacity :=
      (v_slot ->> 'capacity')::integer;

    v_slot_id := nullif(v_slot ->> 'id', '')::bigint;

    if v_end_time <= v_start_time then
      raise exception
        'Each time slot must end after it starts.';
    end if;

    if v_capacity is null
       or v_capacity < 1 then
      raise exception
        'Each time slot must have a capacity of at least one.';
    end if;

    if v_event.id is not null and v_slot_id is not null then
      if v_slot_id = any(v_seen_ids) then
        raise exception 'Each event slot can appear only once.';
      end if;
      v_seen_ids := array_append(v_seen_ids, v_slot_id);
      select * into v_existing_slot
      from public.event_slots
      where id = v_slot_id and event_id = v_event.id
      for update;
      if not found then
        raise exception 'The event slot does not belong to this event.';
      end if;
      select count(*) + public.csr_reserved_spaces(v_slot_id)
      into v_reserved
      from public.bookings
      where event_slot_id = v_slot_id;
      if v_reserved > 0 and (
        v_existing_slot.start_time is distinct from v_start_time
        or v_existing_slot.end_time is distinct from v_end_time
      ) then
        raise exception 'A booked slot cannot change its times.';
      end if;
      if v_capacity < v_reserved then
        raise exception 'Capacity cannot be reduced below reserved places.';
      end if;
      update public.event_slots
      set start_time = v_start_time, end_time = v_end_time, capacity = v_capacity
      where id = v_slot_id;
    else
      insert into public.event_slots (event_id, start_time, end_time, capacity)
      values (v_event.id, v_start_time, v_end_time, v_capacity);
    end if;

  end loop;

  if p_event_id is not null then
    for v_existing_slot in
      select * from public.event_slots
      where event_id = v_event.id
        and not (id = any(v_seen_ids))
      for update
    loop
      if exists (select 1 from public.bookings where event_slot_id = v_existing_slot.id)
        or exists (select 1 from public.corporate_bookings where event_slot_id = v_existing_slot.id) then
        raise exception 'A booked slot cannot be removed.';
      end if;
      delete from public.event_slots where id = v_existing_slot.id;
    end loop;
  end if;

  select
    string_agg(
      to_char(start_time, 'HH24:MI')
      || '-'
      || to_char(end_time, 'HH24:MI'),
      ','
      order by start_time
    ),
    sum(capacity)
  into
    v_time_slots,
    v_total_slots
  from public.event_slots
  where event_id = v_event.id;

  update public.events
  set
    time_slots = v_time_slots,
    total_slots = v_total_slots
  where id = v_event.id
  returning *
  into v_event;

  return v_event;
end;
$function$;

-- Existing admin INSERT/UPDATE policies on bookings must not bypass shared capacity.
-- Status-only attendance updates and legacy NULL-slot rows retain existing behaviour.
create function public.csr_guard_individual_capacity() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_slot public.event_slots%rowtype; v_count bigint;
begin
  if tg_op = 'UPDATE' and new.event_slot_id is not distinct from old.event_slot_id
    and new.event_id is not distinct from old.event_id then return new; end if;
  if new.event_slot_id is null then return new; end if;
  -- Slot locks serialize writers, but cannot refresh a REPEATABLE READ snapshot.
  -- PostgreSQL READ UNCOMMITTED has the same snapshot semantics as READ COMMITTED.
  if pg_catalog.current_setting('transaction_isolation') not in ('read committed', 'read uncommitted') then
    raise exception 'Shared capacity mutations require READ COMMITTED isolation.' using errcode = '25000';
  end if;
  select * into v_slot from public.event_slots where id = new.event_slot_id for update;
  if not found or v_slot.event_id is distinct from new.event_id then raise exception 'Booking event and slot must match.'; end if;
  select count(*) into v_count from public.bookings where event_slot_id = v_slot.id and id <> new.id;
  if v_count + public.csr_reserved_spaces(v_slot.id) + 1 > v_slot.capacity then raise exception 'This time slot is already full.'; end if;
  return new;
end;
$$;
revoke all on function public.csr_guard_individual_capacity() from public, anon, authenticated;
create trigger bookings_shared_capacity before insert or update of event_slot_id,event_id on public.bookings
for each row execute function public.csr_guard_individual_capacity();

-- Direct admin capacity edits already hold the slot row lock; prevent shrinking
-- a slot below reservations or moving a booked slot to a different event.
create function public.csr_guard_slot_capacity() returns trigger
language plpgsql security definer set search_path = '' as $$
declare v_count bigint;
begin
  -- Slot locks serialize writers, but cannot refresh a REPEATABLE READ snapshot.
  -- PostgreSQL READ UNCOMMITTED has the same snapshot semantics as READ COMMITTED.
  if pg_catalog.current_setting('transaction_isolation') not in ('read committed', 'read uncommitted') then
    raise exception 'Shared capacity mutations require READ COMMITTED isolation.' using errcode = '25000';
  end if;
  select count(*) into v_count from public.bookings where event_slot_id = old.id;
  if new.event_id <> old.event_id and (v_count > 0 or exists(select 1 from public.corporate_bookings where event_slot_id = old.id)) then
    raise exception 'A booked slot cannot be moved to another event.';
  end if;
  if new.capacity < v_count + public.csr_reserved_spaces(old.id) then raise exception 'Capacity cannot be reduced below reserved places.'; end if;
  return new;
end;
$$;
revoke all on function public.csr_guard_slot_capacity() from public, anon, authenticated;
create trigger event_slots_shared_capacity before update of capacity,event_id on public.event_slots
for each row execute function public.csr_guard_slot_capacity();

commit;

